services:
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-andareintranet}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-g1w61g6q64ggvv6}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - andareintranet_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - andareintranet_network

  web:
    build: .
    container_name: andareintranet
    command: gunicorn andareintranet.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - andareintranet_network

  celery:
    build: .
    container_name: celery_worker
    command: ["./wait-for-redis.sh", "redis", "celery", "-A", "andareintranet", "worker", "--loglevel=info"]
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - andareintranet_network

volumes:
  postgres_data:

networks:
  andareintranet_network:
    driver: bridge
